### ISSUE TITLE
[Bug] Inline Query fails with Tab key when "mention users without username" is on

### ISSUE THREAD

**Issue by mingtsay** [Sea-n/tdesktop#11]
### Steps to reproduce
1. Turn on `Mention users without username` option in the settings menu.
2. Type the bot name in the . (e.g. `@vote`) 
3. Press Tab key to complete input.

### Expected behaviour
Complete the bot's username instead of a mention link.

### Actual behaviour
The input is replaced with the mention link of the bot's display name.

**Comment by Sea-n** [comment]
Will be fix with next update.
