### ISSUE TITLE
Whether the user profile data should be separated with Telegram application.

### ISSUE THREAD

**Issue by smcdl** [Sea-n/tdesktop#15]
I use Telegram & Telegreat. I want to login into 2 user account respectively. The actuality is telegram and telegreat always use the same user. Could anyone tell me how to do. Thanks.

**Comment by renyhp** [comment]
@smcdl Do you own another phone number that you registered to Telegram? If that's the case, using the portable version of Telegram in any folder, apart from the Telegreat folder, should solve the issue.

If, however, you only own one registered phone number, you can't create another account with the same phone number just by using a different client.

**Comment by Sea-n** [comment]
I think this is solved now
