### ISSUE TITLE
Can change icon?

### ISSUE THREAD

**Issue by zhtw2013** [Sea-n/tdesktop#17]
**Version of Telegreat:** v1.2.20 Alpha

![image](https://user-images.githubusercontent.com/9501406/41214238-db487a56-6d7c-11e8-9896-2ada7092d603.png)

![image](https://user-images.githubusercontent.com/9501406/41214255-f66e0e04-6d7c-11e8-9c76-cb298de3dcb2.png)

作者你好，你不覺得現在的圖示有鋸齒嗎？  原版的更好吧0.0

**Comment by Sea-n** [comment]
I don't know which file is that, unless someone can figure it out, or it won't be fix
