### ISSUE TITLE
[Feature Request] Support Markdown in messages

### ISSUE THREAD

**Issue by AllenGuan** [Sea-n/tdesktop#19]

**Comment by Sea-n** [comment]
I think it's already supported

**Comment by RedMoonOTInetwork** [comment]
@Sea-n Yes

**Comment by RedMoonOTInetwork** [comment]
@Sea-n on Official tdesktop It's already there

**Comment by RedMoonOTInetwork** [comment]
https://t.me/tgbeta/3035

**Comment by AllenGuan** [comment]
Link was not supported.
telegramdesktop/tdesktop#4737

**Comment by Sea-n** [comment]
Oh..

Telegreat Desktop won't support either, Cmd+K is enought for me 😊

**Comment by RedMoonOTInetwork** [comment]
This is for MacOS, right?
