### ISSUE TITLE
remove "mark as read" menu item since it is officially supported

### ISSUE THREAD

**Issue by mingtsay** [Sea-n/tdesktop#20]
The "mark as read" option is now provided by official.
We can simply remove this option we add our own to prevent duplicate it.

Screenshot:
![default](https://user-images.githubusercontent.com/760655/44638896-ad9daa80-a9eb-11e8-9bc3-371db3672fd0.png)

**Comment by Sea-n** [comment]
Will be fixed in next release

Thanks very much 🙇
