### ISSUE TITLE
Detected by antivirus.

### ISSUE THREAD

**Issue by hang333** [Sea-n/tdesktop#23]
### Steps to reproduce
1.  Download tsetup from telegre.at
2.  Kaspersky notice and delete the setup file.
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
https://www.virustotal.com/#/file/5b74e3a0822fc7fc7910ec51e2ac6e41cb35aeab4c6cd0317a7c45cf57d8ed89/detection

### Configuration
**Operating system:**

**Version of Telegreat:** v1.2.8 beta X

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Sea-n** [comment]
Thanks for let me know

But I have no idea about what's going on :cry:

Hope there are someone can point out where is the problem :bowing_man:

**Comment by hang333** [comment]
Not only setup file detected. telegreat.exe also detected...

**Comment by Sea-n** [comment]
@hang333, I heard that, that's what I am so doubted :confused:

**Comment by hang333** [comment]
After I strip your digital signature, it left 3 engines detected it.
https://www.virustotal.com/#/file/50509e25247c7171150f5b0ad96adf4583430ac0af02292d1522158f923d8026/detection

**Comment by hang333** [comment]
This is setup file that stripped digital signature.

[tsetup.1.3.12.alpha.stripped.zip](https://github.com/Sea-n/tdesktop/files/2640343/tsetup.1.3.12.alpha.stripped.zip)

**Comment by Sea-n** [comment]
Interesting :thinking:

**Comment by Sea-n** [comment]
New version released, hope it will not misreport again
