### ISSUE TITLE
windows 10 下中文字体显示不美观

### ISSUE THREAD

**Issue by Seevil** [Sea-n/tdesktop#24]
### Configuration
**Operating system:windows 10 

**Version of Telegreat:** v1.3.12 alpha

中文显示不美观建议使用微软雅黑字体
建议增加字体设置选项？

![tim 20181206164408](https://user-images.githubusercontent.com/7334510/49572395-a84ee500-f976-11e8-9aa9-e837aa40f284.png)

**Comment by Sea-n** [comment]
我在 macOS 看沒這困擾欸

官方未提供相關 API ，歡迎發 Pull Request 提供支援

**Comment by jackiejtr** [comment]
https://github.com/ysc3839/TGFont 可以利用这个项目实现

**Comment by jackiejtr** [comment]
> 我在 macOS 看沒這困擾欸
> 
> 官方未提供相關 API ，歡迎發 Pull Request 提供支援

https://github.com/ysc3839/TGFont 可以利用这个项目实现

**Comment by jackiejtr** [comment]
而且telegreat最新版还没有适配高DPI缩放么 官方版已经跟进了

**Comment by Seevil** [comment]
TGFont 我也找到了并且在使用，但是还是有些瑕疵=。=

**Comment by Sea-n** [comment]
於原始碼未找到相應 API，如擅做改動會使其他使用者出現奇怪 bug

原則上在官方提供此功能前，不做另外支援
