### ISSUE TITLE
Telegreat 1.5.7 bug

### ISSUE THREAD

**Issue by Forden** [Sea-n/tdesktop#26]
### Steps to reproduce

1.1. Open any chat
1.2. Try to write hashtag (#) symbol in message box

2.1. Click searching box
2.2. Try to write hashtag (#) symbol in searching box

### Expected behaviour
Telegreat shouldn't crash.

### Actual behaviour
Telegreat crashes after trying to write hashtag (**#**) symbol in message box or in searching box.

### Configuration
**Operating system:** Windows 10

**Version of Telegreat:** v1.5.7 beta

**Used theme**: Any

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Sea-n** [comment]
Will be fixed in next release (v1.5.8)
