### ISSUE TITLE
[bug] can't see all the toasts options when the windows is at minimum height

### ISSUE THREAD

**Issue by RememberTheAir** [Sea-n/tdesktop#4]
### Steps to reproduce
1. shrink the app window size, as short as possible
2. open the online/typing toast settings

### Expected behaviour
I can see all the available options or I am able to scroll down the list

### Actual behaviour
Can't scroll to the last "supergroups" toggle, so it remains half hidden (I can still click on it, though)

![image](https://user-images.githubusercontent.com/16143208/35579586-479ce104-05e7-11e8-9601-03e8e3e2868e.png)

**Comment by Sea-n** [comment]
Seems I should make it scrollable 🤔

**Comment by pinim** [comment]
I not understand what is the toast option... Can anyone explain briefly?
Also if you can update the lang.strings file to the latest version [5] please...
