### ISSUE TITLE
[feature request] better/more predictable emoji replacement

### ISSUE THREAD

**Issue by RememberTheAir** [Sea-n/tdesktop#6]
Since upstream already confirmed that there won't be more options about emoticons replacement and emoji suggestions (and this is not going to change, I think), I think the idea suggested in #4410 would be a good thing to have on this fork.

Some backstory: people complain that a single settings option ("replace emojis") handles two different things:
- emoticons being replaced with emojis (`<3` becomes ❤️, `xD` becomes 😆)
- emoji suggestions by typing `:this`

...which might be a problem for those who want to have just one of the two things enabled

#4410 suggests to automatically replace strings like `<3` or `xD` into emojis as soon as they are typed (or after a space is added after them), and revert them to classic text emoticons when the user clicks on the backspace. This would mean having a more predictable behaviour (strings are replaced as soon as you type them, and not when you send the message), and to not add an additional checkbox in the settings

**Comment by Sea-n** [comment]
Can I have list of those replasement?

It's big work to create the collection by myself. :P

**Comment by RememberTheAir** [comment]
@Sea-n I'm sorry but I don't have the whole list, it should be somewhere in the sourcecode.

I've found [this old commit](https://github.com/telegramdesktop/tdesktop/commit/d92356ce28b09c4309350a64f7364eb257ad0a9f) about emojis replacements, don't know it it could help. The code related to these replacements surely changed many times

**Comment by Sea-n** [comment]
I think it has been done by upstream 😃 

Ref: https://github.com/telegramdesktop/tdesktop/commit/4b763a7
